### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AmazingDD** [a9r/somecode#1]
能把你fork我的Starbuck-Prediction删除么？
Could you just delete Repository **Starbuck-Prediction** forked from me?

**Comment by a9r** [comment]
ok

YuDi <notifications@github.com> 于 2019年9月3日周二 12:31写道：

**Comment by AmazingDD** [comment]
Really Thx

**Comment by AmazingDD** [comment]
如果你有什么预测相关、特征工程类似的问题可以和我一起讨论，但是这个项目的代码真的麻烦你删一下，涉及到一些敏感信息

**Comment by AmazingDD** [comment]
If you have any question about python, feature engineer or prediction method, we can discuss together. But this repository is a developer version and should not released, so it should better be deleted.
Just hope for your reply soon.

**Comment by AmazingDD** [comment]
I also contact with official Github and they may help me delete the code u forked. But I'm not sure whether it will work, so I still prefer you can delete it. Thx

**Comment by a9r** [comment]
Deleted.
